### ISSUE TITLE
Getting an unbound variableerror with add_on_mod

### ISSUE THREAD

**Issue by mroote** [sdelements/shtdlib#18]
I have a script that watches the nginx SSL directory and reloads if files changed, but I seem to be getting an unbound variable error.

```
/usr/local/bin/shtdlib.sh: line 461: sub_processes[@]: unbound variable
```

The script I'm using is this:

```
   22 reload_nginx() {                                                                                                 
   23     echo "Files modified in certificate directory. Reloading nginx..."                                           
   24     pgrep 'nginx' | xargs kill -SIGHUP                                                                           
   25     echo "Nginx reloaded."                                                                                       
   26 }                                                                                                                
   27                                                                                                                  
   28 # Source shtdlib                                                                                                 
   29 # shellcheck disable=SC1091                                                                                      
   30 source /usr/local/bin/shtdlib.sh                                                                                 
   31                                                                                                                  
   32 add_on_mod reload_nginx "$CERT_DIR"
```

**Comment by mroote** [comment]
I think it's because of the pipe in the command, I'll try without the pipe and see if that works for me.

**Comment by antevens** [comment]
1. You should probably be using pkill instead of pgrep and then calling kill.
2. CERT_DIR should be ${CERT_DIR}
3. If you want to be consistent with our coding practise functions in bash are defined using:
function xxxx {}
rather than:
xxxx() {}
(this makes for easier searching and debugging).

I'm not sure how sub_processes can be unbound when it's declared 3 lines before .... 
Is there any chance you're trying to import this from a bourne (sh) shell rather than a bash shell?

   458             declare -a sub_processes                                            
   459             # Remove stale pids from sub process array                          
   460             live_sub_processes=()                                               
   461             for pid in "${sub_processes[@]}" ; do

**Comment by mroote** [comment]
I tested without the pipe and it seems to work so it doesn't like something about having a callback with pipes in the command. It's running in bash.

1. Good point, I'll switch to pkill then I can drop the pipes.
2. Sure.
3. Shellcheck complains if you use the function keyword as it's not POSIX compliant. I'll add the function keyword but if we want to have this compatible with alpine or other minimal containers without bash we will likely run into issues.

**Comment by mroote** [comment]
I'll add a comment to the add_on_mod function that commands with pipes wont work as the command doesn't run with TTY.
